language: go
go:
    - "1.12"
env:
    - GO111MODULE=on
before_install:
    - go get github.com/mattn/goveralls

jobs:
    include:
        - stage: Run Unit Tests
          script:
              - go test -race -covermode atomic -coverprofile=profile.cov ./...
              - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
        - stage: Build
          script:
              - go build -ldflags "-s -w" -race