version: "3"
services:
    reverse-proxy:
        image: traefik:v2.1
        command:
            - --api.insecure=true
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            - --entryPoints.web.address=:80
            - --entryPoints.internal.address=:8000

        ports:
            - "8080:80"
            - "8081:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    mongodb:
        image: mongo:4.0.10
        labels:
            - traefik.enable=true
            - traefik.http.routers.mongodb.entryPoints=internal

        ports:
            - "27017:27017"
        command: mongod --smallfiles
        hostname: "mongodb"

    user-service:
        build: user-service/.
        depends_on:
            - mongodb
        labels:
            - traefik.enable=true
            - traefik.http.routers.users.rule=Host("localhost")
            - traefik.http.routers.users.rule=PathPrefix("/rest/v1/users") || PathPrefix("/rest/v1/signups") || PathPrefix("/rest/v1/families")
            - traefik.http.services.users.loadbalancer.server.port=8080
    webview-service:
        build: webview-service/.
        depends_on:
            - user-service
        labels:
            - traefik.enable=true
            - traefik.http.routers.webview.rule=Host("localhost")
            - traefik.http.routers.webview.rule=PathPrefix("/")
            - traefik.http.services.webview.loadbalancer.server.port=8080